<a href="https://colab.research.google.com/github/marceloallegri/MiniProjeto_MarceloAllegri_V2/blob/main/notebook%20/C%C3%B3pia_de_analise_exploratoria_varejo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importando Bibliotecas
import pandas as pd
import numpy as np

In [3]:
#Carregando Arquivo csv
df = pd.read_csv("/content/Base Varejo.csv",sep=';',encoding='latin-1')

In [ ]:
#Mostrar informações iniciais
print("--- Informações da Base ---")
print("Prinmeiras 10 linhas do dataset:")
df.head(10)

--- Informações da Base ---
Prinmeiras 10 linhas do dataset:

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN
5,01/02/2019,1000,534,M,4,1,C,187,HIGIENE,HASTES FLEXIVEIS,NaN,NaN,NaN,NaN
6,01/02/2019,1000,534,M,4,1,C,163,ALIMENTOS,MORTADELA,NaN,NaN,NaN,NaN
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
8,01/02/2019,1000,534,M,4,1,C,95,LIMPEZA,AMACIANTE,NaN,NaN,NaN,NaN
9,01/02/2019,1000,534,M,4,1,C,198,BEBIDAS,ENERGETICO,NaN,NaN,NaN,NaN

In [4]:
#Verificando os tipos de dados nas colunas
print(f"Total de registros: {df.shape[0]}")
print(f"Total de colunas: {df.shape[1]}")
print(" Tipo de dado de cada coluna:")
print(df.dtypes)

Total de registros: 54511
Total de colunas: 14
 Tipo de dado de cada coluna:
DATA            object
CO_ID          float64
CL_ID          float64
CL_GENERO       object
CL_EC          float64
CL_FHL         float64
CL_SEG          object
PR_ID          float64
PR_CAT          object
PR_NOME         object
Unnamed: 10    float64
Unnamed: 11    float64
Unnamed: 12    float64
Unnamed: 13    float64
dtype: object

In [5]:
# Verificação de nulos e duplicatas
print("\n--- Verificação de Problemas ---")
print("Valores nulos por coluna:\n", df.isnull().sum())
print("Total de duplicatas:", df.duplicated().sum())

--- Verificação de Problemas ---
Valores nulos por coluna:
 DATA               0
CO_ID              1
CL_ID              1
CL_GENERO          1
CL_EC              1
CL_FHL             1
CL_SEG             1
PR_ID              1
PR_CAT             1
PR_NOME            1
Unnamed: 10    54511
Unnamed: 11    54511
Unnamed: 12    54511
Unnamed: 13    54511
dtype: int64
Total de duplicatas: 6358

Após analise inicial dos dados podemos observar 4 colunas com valores Nulos superior a 90% dos registros da referida coluna. Essas colunas deverão ser removidas na etapa de limpeza. A coluna DATA contem dados do tipo object, esta coluna deve ser convertida para o tipo datetime para permitir análises com base no tempo. Com relação aos dados duplicados, foram encontrados 96.553 registros duplicados dos 830.000, esses dados deverão ser avaliados durante a etapa de limpeza para não haver distorção nas análises.

In [6]:
#Convertendo coluna data
df['DATA'] = pd.to_datetime(df['DATA'], dayfirst=True, errors='coerce')
df['DATA'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 54511 entries, 0 to 54510
Series name: DATA
Non-Null Count  Dtype
--------------  -----
54510 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 426.0 KB

In [7]:
#Removendo colunas com valores nulos
print("Dimensão do DF antes da remoção das colunas vazias:")
print(df.shape)
df = df.dropna(axis=1, how='all')
print("Dimensão do DF depois da remoção das colunas vazias:")
print(df.shape)

Dimensão do DF antes da remoção das colunas vazias:
(54511, 14)
Dimensão do DF depois da remoção das colunas vazias:
(54511, 10)

In [8]:
#Removendo linhas duplicadas
print(f"Dimensão do DF antes da remoção das linhas duplicadas: {(df.shape)}")

df = df.drop_duplicates()
print(f"Dimensão do DF depois da remoção das linhas duplicadas: {(df.shape)}")

Dimensão do DF antes da remoção das linhas duplicadas: (54511, 10)
Dimensão do DF depois da remoção das linhas duplicadas: (48153, 10)

In [9]:
#Tratando dados na coluna categoria
df['PR_CAT'] = df['PR_CAT'].fillna("SEM CATEGORIA")
df['PR_CAT'] = df['PR_CAT'].replace('#N/D', 'SEM CATEGORIA')

In [10]:
#Salvando base de dados limpa
df.to_csv('/content/base_varejo_limpa.csv', index=False, sep=';')

Após a etapa de limpeza pode ser iniciada a analise estatística das colunas.

In [11]:
# --- Estatística Descritiva ---
#Coluna de número de filhos
df['CL_FHL'].describe()

count    48152.000000
mean         1.130316
std          1.401344
min          0.000000
25%          0.000000
50%          0.000000
75%          2.000000
max          4.000000
Name: CL_FHL, dtype: float64

Podemos verificar que a média do número de filhos é 1 e o comprador com mais filhos é 4.

In [12]:
# --- Agrupamentos ---
#Gênero com mais compras
df['CL_GENERO'].value_counts()

CL_GENERO
F    25188
M    22964
Name: count, dtype: int64

Se analisarmos o gênero do comprador podemos verificar que o sexo feminino efetuou o maior número das compras do banco de dados.

In [13]:
#Categoria com mais pedidos
df.groupby('PR_CAT').size().sort_values(ascending=False)

PR_CAT
ALIMENTOS        25291
HIGIENE           8951
LIMPEZA           8487
BEBIDAS           2473
PET               1885
ACESSORIOS         841
SEM CATEGORIA      225
dtype: int64

Podemos verificar que os itens com maior volume de venda são Alimentos, Higiene e Limpeza.

In [14]:
#Agrupando por gênero do comprador e categoria do produto
df.groupby(['CL_GENERO', 'PR_CAT']).size()

CL_GENERO  PR_CAT
F          ACESSORIOS         462
           ALIMENTOS        13164
           BEBIDAS           1287
           HIGIENE           4642
           LIMPEZA           4516
           PET               1002
           SEM CATEGORIA      115
M          ACESSORIOS         379
           ALIMENTOS        12127
           BEBIDAS           1186
           HIGIENE           4309
           LIMPEZA           3971
           PET                883
           SEM CATEGORIA      109
dtype: int64

Ao fazer o agrupamento por gênero do comprador e categoria do produto podemos observar que o gênero feminino comprou mais que o masculino em todas as categorias.